### ISSUE TITLE
Instructions about deploying it?

### ISSUE THREAD

**Issue by avinassh** [rot-13/ltt#6]
Can you add some instructions about how to deploy it? would be nice for a budding devs like me

**Comment by ShayDavidson** [comment]
Do you mean how to run it locally or how to deploy it to a remote server?

**Comment by avinassh** [comment]
may be heroku? or openshift?

**Comment by ShayDavidson** [comment]
Can be easily deployed to heroku as it is. You just need to run `grunt` to generate the `public` folder, and then deploy.
